version: '3.8'

services:
  # PostgreSQL 데이터베이스 서비스
  postgres:
    image: postgres-image # 이미지 이름 접두사 제외
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - spring-network

  ### TODO: 아직 도커 네트워크 문제가 있어 컴포즈 기능은 사용이 어려움
  # Spring Boot 애플리케이션 서비스
  server:
    image: spring-boilerplate-image # 이미지 이름 접두사 제외
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boilerplate-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring-network

volumes:
  db_data:

networks:
  spring-network:
    name: spring-network # 네트워크 이름 접두사 제외
    driver: bridge
#    external: true # 직접 네트워크를 생성했을 경우 true, 아니면 false