# Spring Boot application properties
spring:
  # environment variables
  config:
    import: optional:file:.env[.properties]
  # database configuration - postgresql
  datasource:
    url: jdbc:postgresql://postgres:5432/boilerplate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework: trace